import Link from "next/link";
import { AdminActionButton } from "@/components/admin/AdminActionButton";
import { requireAdminDb } from "@/lib/auth/admin";
import { getHostApplications } from "@/repositories/adminRepository";

export const dynamic = "force-dynamic";

export default async function HostApplicationsPage({searchParams}:{searchParams:Promise<{status?:string}>}) {
  const status = (await searchParams).status ?? "all";
  const rows = await getHostApplications(await requireAdminDb(), status);
  const filters = [["all","\uC804\uCCB4"],["pending","\uC2B9\uC778 \uB300\uAE30"],["approved","\uC2B9\uC778 \uC644\uB8CC"],["rejected","\uBC18\uB824"]];
  return <><div className="section-heading page-heading"><div><p className="eyebrow">Verification</p><h1>{"\uACF5\uAC04 \uC6B4\uC601\uC790 \uC2E0\uCCAD \uAD00\uB9AC"}</h1></div><div className="management-actions">{filters.map(([value,label])=><Link className={`btn btn-small ${status===value?"btn-primary":"btn-ghost"}`} href={`/admin/host-applications?status=${value}`} key={value}>{label}</Link>)}</div></div><div className="admin-list">{rows.length?rows.map((item)=><article className="panel" key={item.id}><div className="section-heading"><div><span className={`tag application-${item.status}`}>{item.status}</span><h2>{item.spaceName}</h2><p className="muted">{item.applicantName} / {item.email}</p></div><small>{new Date(item.createdAt).toLocaleDateString("ko-KR")}</small></div><div className="detail-info-grid"><div className="detail-item"><span>{"\uACF5\uAC04 \uC8FC\uC18C"}</span><strong>{item.spaceAddress}</strong></div><div className="detail-item"><span>{"\uC720\uD615 / \uAD00\uACC4"}</span><strong>{item.spaceType} / {item.relationship}</strong></div><div className="detail-item"><span>승인 후 협의 연락처</span><strong>{item.negotiationContactMethod ?? "기존 신청"} · {item.negotiationContactValue ?? item.phone}</strong></div>{item.evidencePaths.length>0&&<div className="detail-item"><span>{"\uC99D\uBE59 \uC790\uB8CC"}</span><div className="management-actions">{item.evidencePaths.map((_,index)=><a href={`/api/admin/host-applications/${item.id}/evidence?index=${index}`} target="_blank" rel="noopener noreferrer" key={index}>{index+1}번 자료 열기</a>)}</div></div>}</div>{item.message&&<p><strong>추가 전달 사항</strong><br/>{item.message}</p>}{item.rejectionReason&&<p className="error-summary">{"\uBC18\uB824 \uC0AC\uC720"}: {item.rejectionReason}</p>}{item.status==="pending"&&<div className="management-actions"><AdminActionButton action="approve_host" targetId={item.id} label={"\uC2B9\uC778"}/><AdminActionButton action="reject_host" targetId={item.id} label={"\uBC18\uB824"} danger requiresReason/></div>}</article>):<div className="empty">{"\uD574\uB2F9 \uC0C1\uD0DC\uC758 \uC2E0\uCCAD\uC774 \uC5C6\uC2B5\uB2C8\uB2E4."}</div>}</div></>;
}
