"use client";
import { useEffect, useState } from "react";
import { Pencil, Plus, Trash2 } from "lucide-react";
import { createBrowserSupabaseClient } from "@/lib/supabase/client";
import { createSchedule, deleteSchedule, listSchedules, updateSchedule } from "@/repositories/scheduleRepository";
import type { Community } from "@/types/community";
import type { Schedule } from "@/types/operator";

const blank = (): Omit<Schedule, "id" | "createdAt" | "updatedAt"> => ({ communityId: "", title: "", communityName: "", date: "", startTime: "", endTime: "", location: "", description: "", capacity: undefined, status: "upcoming" });
export default function Page() {
  const [items, setItems] = useState<Schedule[]>([]), [communities, setCommunities] = useState<Community[]>([]), [editing, setEditing] = useState<Schedule | null>(null), [form, setForm] = useState(blank()), [open, setOpen] = useState(false), [loading, setLoading] = useState(true), [error, setError] = useState("");
  useEffect(() => { Promise.all([listSchedules(createBrowserSupabaseClient()), fetch("/api/communities", { cache: "no-store" }).then((response) => response.json())]).then(([schedules, owned]) => { setItems(schedules); setCommunities(owned); }).catch(() => setError("일정을 불러오지 못했어요.")).finally(() => setLoading(false)); }, []);
  function show(item?: Schedule) { setEditing(item ?? null); setForm(item ?? blank()); setError(""); setOpen(true); }
  async function save() { if (!form.communityId || !form.title || !form.date || !form.startTime || !form.location) return setError("커뮤니티, 일정명, 날짜, 시작 시간, 장소는 필수예요."); const community = communities.find((item) => item.id === form.communityId); if (!community) return setError("내 커뮤니티를 선택해 주세요."); const value = { ...form, communityName: community.name }; const db = createBrowserSupabaseClient(); try { const saved = editing ? await updateSchedule(db, editing.id, value) : await createSchedule(db, value); setItems(editing ? items.map((item) => item.id === saved.id ? saved : item) : [...items, saved]); setOpen(false); } catch { setError("일정을 저장하지 못했어요."); } }
  async function remove(id: string) { if (!confirm("이 일정을 삭제할까요?")) return; await deleteSchedule(createBrowserSupabaseClient(), id); setItems(items.filter((item) => item.id !== id)); }
  if (loading) return <section className="section"><div className="container">일정을 불러오는 중...</div></section>;
  return <section className="section"><div className="container"><div className="meta" style={{ justifyContent: "space-between" }}><div><p className="eyebrow">Schedule</p><h1 className="section-title">내 커뮤니티 일정</h1></div><button className="btn btn-primary" onClick={() => show()}><Plus />일정 추가</button></div>{error && <p className="error-summary">{error}</p>}{items.length ? <div className="grid">{[...items].sort((a, b) => a.date.localeCompare(b.date)).map((item) => <article className="panel" key={item.id}><div className="meta" style={{ justifyContent: "space-between" }}><span className="tag">{item.communityName}</span><span><button aria-label="수정" onClick={() => show(item)}><Pencil size={17} /></button><button aria-label="삭제" onClick={() => void remove(item.id)}><Trash2 size={17} /></button></span></div><h3>{item.title}</h3><p>{item.date} · {item.startTime}{item.endTime && `–${item.endTime}`} · {item.location}</p></article>)}</div> : <div className="empty"><h3>내 커뮤니티 일정이 없어요.</h3></div>}{open && <div className="dialog-backdrop"><div className="dialog"><h2>{editing ? "일정 수정" : "새 일정"}</h2><div className="form"><label>커뮤니티<select className="field" value={form.communityId ?? ""} disabled={Boolean(editing)} onChange={(event) => setForm({ ...form, communityId: event.target.value, communityName: communities.find((item) => item.id === event.target.value)?.name ?? "" })}><option value="">선택</option>{communities.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>일정명<input className="field" value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} /></label><div className="grid form-grid"><label>날짜<input type="date" className="field" value={form.date} onChange={(event) => setForm({ ...form, date: event.target.value })} /></label><label>시작 시간<input type="time" className="field" value={form.startTime} onChange={(event) => setForm({ ...form, startTime: event.target.value })} /></label><label>종료 시간<input type="time" className="field" value={form.endTime} onChange={(event) => setForm({ ...form, endTime: event.target.value })} /></label></div><label>장소<input className="field" value={form.location} onChange={(event) => setForm({ ...form, location: event.target.value })} /></label><label>설명<textarea className="field" value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></label><div className="meta"><button className="btn btn-primary" onClick={() => void save()}>저장</button><button className="btn btn-ghost" onClick={() => setOpen(false)}>취소</button></div></div></div></div>}</div></section>;
}
