import "server-only";
import type { SupabaseClient } from "@supabase/supabase-js";
import type { AdminAudit,AdminMember,AdminStats,SpaceHostApplication } from "@/types/admin";

const mapApplication=(r:any):SpaceHostApplication=>({id:r.id,userId:r.user_id,applicantName:r.applicant_name,email:r.email,phone:r.phone,spaceName:r.space_name,spaceAddress:r.space_address,spaceType:r.space_type,relationship:r.relationship,relatedLink:r.related_link,message:r.message,evidencePath:r.evidence_path,evidencePaths:Array.isArray(r.evidence_paths)&&r.evidence_paths.length?r.evidence_paths:r.evidence_path?[r.evidence_path]:[],negotiationContactMethod:r.negotiation_contact_method??null,negotiationContactValue:r.negotiation_contact_value??null,status:r.status,rejectionReason:r.rejection_reason,reviewedBy:r.reviewed_by,reviewedAt:r.reviewed_at,createdAt:r.created_at,updatedAt:r.updated_at});
export async function getMyLatestHostApplication(db:SupabaseClient,userId:string){const{data,error}=await db.from("space_host_applications").select("*").eq("user_id",userId).order("created_at",{ascending:false}).limit(1).maybeSingle();if(error)throw error;return data?mapApplication(data):null;}
export async function getApprovedSpaceHostAddress(db:SupabaseClient,userId:string){const{data,error}=await db.from("space_host_applications").select("space_address").eq("user_id",userId).eq("status","approved").order("reviewed_at",{ascending:false}).limit(1).maybeSingle();if(error)throw error;return data?.space_address?.trim()||"";}
export async function getApprovedSpaceHostDefaults(db:SupabaseClient,userId:string){const{data,error}=await db.from("space_host_applications").select("space_address,negotiation_contact_method,negotiation_contact_value").eq("user_id",userId).eq("status","approved").order("reviewed_at",{ascending:false}).limit(1).maybeSingle();if(error)throw error;return{address:data?.space_address?.trim()||"",contactMethod:data?.negotiation_contact_method??null,contactValue:data?.negotiation_contact_value?.trim()||""};}
export async function getAdminStats(db:SupabaseClient):Promise<AdminStats>{const [members,pendingHosts,spaces,communities,reports]=await Promise.all([db.from("profiles").select("id",{count:"exact",head:true}),db.from("space_host_applications").select("id",{count:"exact",head:true}).eq("status","pending"),db.from("spaces").select("id",{count:"exact",head:true}),db.from("communities").select("id",{count:"exact",head:true}),db.from("reports").select("id",{count:"exact",head:true}).in("status",["pending","reviewing"])]);for(const r of [members,pendingHosts,spaces,communities,reports])if(r.error)throw r.error;return{members:members.count??0,pendingHosts:pendingHosts.count??0,spaces:spaces.count??0,communities:communities.count??0,pendingReports:reports.count??0};}
export async function getHostApplications(db:SupabaseClient,status?:string){let q=db.from("space_host_applications").select("*").order("created_at",{ascending:false});if(status&&status!=="all")q=q.eq("status",status);const{data,error}=await q;if(error?.code==="PGRST205"||error?.code==="42P01")return[];if(error)throw error;return(data??[]).map(mapApplication);}
export async function getAdminMembers(db:SupabaseClient):Promise<AdminMember[]>{let result=await db.from("profiles").select("id,email,nickname,roles,account_status,community_host_revoked_at,community_host_revocation_reason,created_at").order("created_at",{ascending:false});if(result.error?.code==="42703")result=await db.from("profiles").select("id,email,nickname,roles,created_at").order("created_at",{ascending:false}) as typeof result;if(result.error)throw result.error;return(result.data??[]).map((r:any)=>({id:r.id,email:r.email,nickname:r.nickname,roles:r.roles??["member"],accountStatus:r.account_status??"active",communityHostRevokedAt:r.community_host_revoked_at??null,communityHostRevocationReason:r.community_host_revocation_reason??null,createdAt:r.created_at}));}
export async function getAdminSpaces(db:SupabaseClient){let result=await db.from("spaces").select("id,name,owner_id,main_region,space_type,status,created_at,deleted_at,moderation_reason").order("created_at",{ascending:false});if(result.error?.code==="42703")result=await db.from("spaces").select("id,name,owner_id,main_region,space_type,status,created_at").order("created_at",{ascending:false}) as typeof result;if(result.error)throw result.error;return(result.data??[]).map((row:any)=>({deleted_at:null,moderation_reason:null,...row}));}
export async function getAdminCommunities(db:SupabaseClient){let result=await db.from("communities").select("id,name,owner_id,category,main_region,status,report_count,created_at,deleted_at,moderation_reason").order("created_at",{ascending:false});if(result.error?.code==="42703")result=await db.from("communities").select("id,name,owner_id,category,main_region,status,created_at").order("created_at",{ascending:false}) as typeof result;if(result.error)throw result.error;return(result.data??[]).map((row:any)=>({report_count:0,deleted_at:null,moderation_reason:null,...row}));}
export async function getAdminReports(db:SupabaseClient){const{data,error}=await db.from("reports").select("*").order("created_at",{ascending:false});if(error?.code==="PGRST205"||error?.code==="42P01")return[];if(error)throw error;return data??[];}
export async function getAdminAudit(db:SupabaseClient):Promise<AdminAudit[]>{const{data,error}=await db.from("admin_audit_logs").select("*").order("created_at",{ascending:false}).limit(200);if(error?.code==="PGRST205"||error?.code==="42P01")return[];if(error)throw error;return(data??[]).map((r:any)=>({id:r.id,adminId:r.admin_id,actionType:r.action_type,targetType:r.target_type,targetId:r.target_id,reason:r.reason,createdAt:r.created_at}));}
export async function getSpaceVerificationRequests(db:SupabaseClient,status?:string){const relation=status==="suspended"?"spaces!inner(id,name,address,address_detail,space_type,thumbnail_url,status,owner_id)":"spaces(id,name,address,address_detail,space_type,thumbnail_url,status,owner_id)";let query=db.from("space_verification_requests").select(`*,${relation}`).order("created_at",{ascending:false});if(status==="suspended")query=query.eq("spaces.status","suspended");else if(status&&status!=="all")query=query.eq("status",status);const{data,error}=await query;if(error?.code==="PGRST205"||error?.code==="42P01")return[];if(error)throw error;return data??[];}
export async function getSpaceVerificationRequest(db:SupabaseClient,id:string){const{data,error}=await db.from("space_verification_requests").select("*,spaces(*,space_images(*)),space_verification_files(*)").eq("id",id).maybeSingle();if(error)throw error;return data;}
