import type { SupabaseClient } from "@supabase/supabase-js";
import type { Schedule } from "@/types/operator";

const map = (row: any): Schedule => ({ id: row.id, communityId: row.community_id, title: row.title, communityName: row.community_name, date: row.date, startTime: row.start_time, endTime: row.end_time ?? undefined, location: row.location, description: row.description ?? undefined, capacity: row.capacity ?? undefined, status: row.status, createdAt: row.created_at, updatedAt: row.updated_at });
const payload = (value: Partial<Schedule>) => ({ community_id: value.communityId, title: value.title, community_name: value.communityName, date: value.date, start_time: value.startTime, end_time: value.endTime || null, location: value.location, description: value.description || null, capacity: value.capacity ?? null, status: value.status });

export async function getSchedulesForMyCommunities(db: SupabaseClient) { const { data: { user } } = await db.auth.getUser(); if (!user) throw new Error("AUTH_REQUIRED"); const { data, error } = await db.from("schedules").select("*,communities!inner(owner_id)").eq("communities.owner_id", user.id).order("date"); if (error) throw error; return (data ?? []).map(map); }
export const listSchedules = getSchedulesForMyCommunities;
export async function createScheduleForMyCommunity(db: SupabaseClient, value: Omit<Schedule, "id" | "createdAt" | "updatedAt">) { if (!value.communityId) throw new Error("COMMUNITY_REQUIRED"); const { data, error } = await db.from("schedules").insert(payload(value)).select().single(); if (error) throw error; return map(data); }
export const createSchedule = createScheduleForMyCommunity;
export async function updateMySchedule(db: SupabaseClient, id: string, value: Partial<Schedule>) { const { data, error } = await db.from("schedules").update(payload(value)).eq("id", id).select().maybeSingle(); if (error) throw error; if (!data) throw new Error("SCHEDULE_NOT_FOUND"); return map(data); }
export const updateSchedule = updateMySchedule;
export async function deleteMySchedule(db: SupabaseClient, id: string) { const { error } = await db.from("schedules").delete().eq("id", id); if (error) throw error; }
export const deleteSchedule = deleteMySchedule;

function scheduleValues(value: { communityId: string; communityName: string; nextMeetingAt: string; meetingEndAt?: string | null; location: string; capacity: number }) { const start = new Date(value.nextMeetingAt), end = value.meetingEndAt ? new Date(value.meetingEndAt) : null; const date = new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Seoul", year: "numeric", month: "2-digit", day: "2-digit" }).format(start); const time = (input: Date) => new Intl.DateTimeFormat("en-GB", { timeZone: "Asia/Seoul", hour: "2-digit", minute: "2-digit", hourCycle: "h23" }).format(input); return { community_id: value.communityId, community_name: value.communityName, title: `${value.communityName} 첫 모임`, date, start_time: time(start), end_time: end ? time(end) : null, location: value.location, capacity: value.capacity, status: "upcoming" }; }
export async function createInitialCommunitySchedule(db: SupabaseClient, value: { communityId: string; communityName: string; nextMeetingAt: string; meetingEndAt?: string | null; location: string; capacity: number }) { const { error } = await db.from("schedules").insert(scheduleValues(value)); if (error) throw error; }
export async function syncInitialCommunitySchedule(db: SupabaseClient, value: { communityId: string; communityName: string; nextMeetingAt: string; meetingEndAt?: string | null; location: string; capacity: number }) { const { data, error } = await db.from("schedules").select("id").eq("community_id", value.communityId).order("created_at").limit(1).maybeSingle(); if (error) throw error; if (!data) return createInitialCommunitySchedule(db, value); const result = await db.from("schedules").update(scheduleValues(value)).eq("id", data.id); if (result.error) throw result.error; }
