import type { SupabaseClient } from "@supabase/supabase-js";
import type { CreateSpaceInput, Space, SpaceImage, SpaceStatus, UpdateSpaceInput } from "@/types/space";

const image = (row: any): SpaceImage => ({ id: row.id, spaceId: row.space_id, storagePath: row.storage_path, publicUrl: row.public_url, fileName: row.file_name, mimeType: row.mime_type, fileSize: row.file_size, width: row.width, height: row.height, sortOrder: row.sort_order, isThumbnail: row.is_thumbnail, createdAt: row.created_at });
const map = (row: any): Space => ({ id: row.id, ownerId: row.owner_id, operatorId: row.operator_id, name: row.name, slug: row.slug, spaceType: row.space_type, shortDescription: row.short_description, description: row.description, mainRegion: row.main_region, detailedRegion: row.detailed_region, customRegion: row.custom_region, address: row.address, addressDetail: row.address_detail, pricePerHour: row.price_per_hour, minimumHours: row.minimum_hours, suitableCapacity: row.suitable_capacity, maxCapacity: row.max_capacity, availableDays: row.available_days ?? [], availableStartTime: row.available_start_time, availableEndTime: row.available_end_time, regularUseAvailable: row.regular_use_available, facilities: row.facilities ?? [], moods: row.moods ?? [], suitableActivities: row.suitable_activities ?? [], noiseLevel: row.noise_level, foodAllowed: row.food_allowed, alcoholAllowed: row.alcohol_allowed, furnitureMovable: row.furniture_movable, parkingAvailable: row.parking_available, thumbnailUrl: row.thumbnail_url, status: row.status, images: (row.space_images ?? []).map(image).sort((a: SpaceImage, b: SpaceImage) => a.sortOrder - b.sortOrder), analysisUpdatedAt: Array.isArray(row.space_analysis) ? row.space_analysis[0]?.updated_at ?? null : row.space_analysis?.updated_at ?? null, createdAt: row.created_at, updatedAt: row.updated_at });
const payload = (values: UpdateSpaceInput) => ({ name: values.name, space_type: values.spaceType, short_description: values.shortDescription, description: values.description, main_region: values.mainRegion, detailed_region: values.detailedRegion, custom_region: values.detailedRegion === "기타" ? values.customRegion || null : null, address: values.address, address_detail: values.addressDetail, price_per_hour: values.pricePerHour, minimum_hours: values.minimumHours, suitable_capacity: values.suitableCapacity, max_capacity: values.maxCapacity, available_days: values.availableDays, available_start_time: values.availableStartTime || null, available_end_time: values.availableEndTime || null, regular_use_available: values.regularUseAvailable, facilities: values.facilities, moods: values.moods, suitable_activities: values.suitableActivities, noise_level: values.noiseLevel, food_allowed: values.foodAllowed, alcohol_allowed: values.alcoholAllowed, furniture_movable: values.furnitureMovable, parking_available: values.parkingAvailable, status: values.status });

async function currentUserId(db: SupabaseClient) {
  const { data: { user }, error } = await db.auth.getUser();
  if (error || !user) throw new Error("AUTH_REQUIRED");
  return user.id;
}
function createSlug(name: string) {
  const base = name.toLowerCase().trim().replace(/[^a-z0-9가-힣]+/g, "-").replace(/^-|-$/g, "") || "space";
  return `${base}-${crypto.randomUUID().slice(0, 8)}`;
}

export async function getActiveSpaces(db: SupabaseClient) { const { data, error } = await db.from("spaces").select("*,space_images(*)").eq("status", "active").order("created_at", { ascending: false }); if (error) throw error; return (data ?? []).map(map); }
export async function getSpaceBySlug(db: SupabaseClient, slug: string) { const { data, error } = await db.from("spaces").select("*,space_images(*)").eq("slug", slug).eq("status", "active").maybeSingle(); if (error) throw error; return data ? map(data) : null; }
export async function getSpaceById(db: SupabaseClient, id: string) { const { data, error } = await db.from("spaces").select("*,space_images(*)").eq("id", id).maybeSingle(); if (error) throw error; return data ? map(data) : null; }

export async function getMySpaces(db: SupabaseClient) { const ownerId = await currentUserId(db); const { data, error } = await db.from("spaces").select("*,space_images(*),space_analysis(id,updated_at)").eq("owner_id", ownerId).order("updated_at", { ascending: false }); if (error) throw error; return (data ?? []).map(map); }
export const getSpacesForDashboard = getMySpaces;
export async function getMySpaceById(db: SupabaseClient, id: string) { const ownerId = await currentUserId(db); const { data, error } = await db.from("spaces").select("*,space_images(*),space_analysis(id,updated_at)").eq("id", id).eq("owner_id", ownerId).maybeSingle(); if (error) throw error; return data ? map(data) : null; }

export async function createSpaceForCurrentUser(db: SupabaseClient, values: CreateSpaceInput) { const ownerId = await currentUserId(db); const { data, error } = await db.from("spaces").insert({ ...payload(values), owner_id: ownerId, operator_id: null, slug: createSlug(values.name) }).select("*,space_images(*)").single(); if (error) throw error; return map(data); }
export const createSpace = createSpaceForCurrentUser;
export async function updateMySpace(db: SupabaseClient, id: string, values: UpdateSpaceInput) { const ownerId = await currentUserId(db); const { data, error } = await db.from("spaces").update(payload(values)).eq("id", id).eq("owner_id", ownerId).select("*,space_images(*)").maybeSingle(); if (error) throw error; if (!data) throw new Error("SPACE_NOT_FOUND"); return map(data); }
export const updateSpace = updateMySpace;
export async function changeSpaceStatus(db: SupabaseClient, id: string, status: SpaceStatus) { const ownerId = await currentUserId(db); const { error } = await db.from("spaces").update({ status }).eq("id", id).eq("owner_id", ownerId); if (error) throw error; }
export async function createSpaceImage(db: SupabaseClient, values: Omit<SpaceImage, "id" | "createdAt">) { const { data, error } = await db.from("space_images").insert({ space_id: values.spaceId, storage_path: values.storagePath, public_url: values.publicUrl, file_name: values.fileName, mime_type: values.mimeType, file_size: values.fileSize, width: values.width, height: values.height, sort_order: values.sortOrder, is_thumbnail: values.isThumbnail }).select().single(); if (error) throw error; return image(data); }
export async function deleteSpaceImage(db: SupabaseClient, id: string) { const { error } = await db.from("space_images").delete().eq("id", id); if (error) throw error; }
export async function reorderSpaceImages(db: SupabaseClient, ids: string[]) { await Promise.all(ids.map((id, sortOrder) => db.from("space_images").update({ sort_order: sortOrder }).eq("id", id))); }
export async function setThumbnailImage(db: SupabaseClient, spaceId: string, imageId: string, url: string) { const ownerId = await currentUserId(db); await db.from("space_images").update({ is_thumbnail: false }).eq("space_id", spaceId); const { error } = await db.from("space_images").update({ is_thumbnail: true }).eq("id", imageId).eq("space_id", spaceId); if (error) throw error; const update = await db.from("spaces").update({ thumbnail_url: url }).eq("id", spaceId).eq("owner_id", ownerId); if (update.error) throw update.error; }
export async function deleteMySpace(db: SupabaseClient, id: string) { const ownerId = await currentUserId(db); const space = await getMySpaceById(db, id); if (!space) return; if (space.images.length) { const { error } = await db.storage.from("space-images").remove(space.images.map((item) => item.storagePath)); if (error) throw new Error("STORAGE_DELETE_FAILED"); } const { error } = await db.from("spaces").delete().eq("id", id).eq("owner_id", ownerId); if (error) throw error; }
export const deleteSpace = deleteMySpace;
