"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { CheckCircle2, X } from "lucide-react";

type CommunityForApplication = { id: string; name: string; slug: string; questions: string[]; canApply: boolean; disabledReason?: string; nextMeetingAt?: string | null };
export function ApplicationForm({ community, applicant }: { community: CommunityForApplication; applicant?: { nickname: string; email: string } | null }) {
  const router = useRouter();
  const [open, setOpen] = useState(false), [values, setValues] = useState({ applicantName: applicant?.nickname ?? "", applicantContact: applicant?.email ?? "", introduction: "", motivation: "", privacyAgreed: false }), [answers, setAnswers] = useState<Record<string, string>>({}), [loading, setLoading] = useState(false), [error, setError] = useState(""), [done, setDone] = useState<{ receipt: string } | null>(null);
  function start() { if (!applicant) { router.push(`/login?next=${encodeURIComponent(`/communities/${community.slug}`)}`); return; } setOpen(true); }
  async function submit(event: React.FormEvent) { event.preventDefault(); setLoading(true); setError(""); try { const response = await fetch(`/api/communities/${community.id}/applications`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...values, answers }) }); const result = await response.json(); if (!response.ok) throw new Error(result.message); setDone(result); } catch (caught) { setError(caught instanceof Error ? caught.message : "신청하지 못했어요."); } finally { setLoading(false); } }
  return <><button type="button" className="btn btn-primary" style={{ width: "100%" }} disabled={!community.canApply} onClick={start}>{community.canApply ? applicant ? "참여 신청" : "로그인하고 참여 신청" : "신청 불가"}</button>{!community.canApply && <p className="muted">{community.disabledReason}</p>}{open && <div className="dialog-backdrop"><div className="dialog" style={{ width: "min(620px,calc(100% - 32px))", maxHeight: "90vh", overflow: "auto" }}><button type="button" aria-label="닫기" style={{ float: "right", border: 0, background: "transparent" }} onClick={() => setOpen(false)}><X /></button>{done ? <div style={{ textAlign: "center" }}><CheckCircle2 size={54} color="var(--success)" /><h2>참여 신청이 완료됐어요</h2><p><b>{community.name}</b> 운영자가 확인한 뒤 안내해 드립니다.</p><p className="tag">접수번호 {done.receipt}</p><button className="btn btn-primary" onClick={() => setOpen(false)}>커뮤니티 다시 보기</button></div> : <form className="form" onSubmit={submit}><h2>{community.name} 참여 신청</h2><label>이름 또는 닉네임<input className="field" required value={values.applicantName} onChange={(event) => setValues({ ...values, applicantName: event.target.value })} /></label><label>연락처<input className="field" required value={values.applicantContact} onChange={(event) => setValues({ ...values, applicantContact: event.target.value })} /></label><label>간단한 자기소개<textarea className="field" required minLength={5} rows={3} value={values.introduction} onChange={(event) => setValues({ ...values, introduction: event.target.value })} /></label><label>참여 동기<textarea className="field" required minLength={5} rows={3} value={values.motivation} onChange={(event) => setValues({ ...values, motivation: event.target.value })} /></label>{community.questions.map((question) => <label key={question}>{question}<textarea className="field" rows={2} value={answers[question] ?? ""} onChange={(event) => setAnswers({ ...answers, [question]: event.target.value })} /></label>)}<label style={{ display: "flex", alignItems: "center" }}><input type="checkbox" required checked={values.privacyAgreed} onChange={(event) => setValues({ ...values, privacyAgreed: event.target.checked })} /> 참여 신청 처리를 위한 개인정보 수집에 동의합니다.</label>{error && <p className="error-summary">{error}</p>}<button className="btn btn-primary" disabled={loading}>{loading ? "신청 저장 중..." : "신청 완료"}</button></form>}</div></div>}</>;
}
