import Link from"next/link";import type{ButtonHTMLAttributes,InputHTMLAttributes,ReactNode,SelectHTMLAttributes}from"react";
type ButtonProps=ButtonHTMLAttributes<HTMLButtonElement>&{variant?:"primary"|"secondary"|"ghost"};
export function Button({variant="primary",className="",...props}:ButtonProps){return <button className={`btn ${variant==="primary"?"btn-primary":"btn-ghost"} ${className}`} {...props}/>}
export function ButtonLink({href,children,variant="primary",className=""}:{href:string;children:ReactNode;variant?:"primary"|"secondary"|"ghost";className?:string}){return <Link href={href} className={`btn ${variant==="primary"?"btn-primary":"btn-ghost"} ${className}`}>{children}</Link>}
export function Card({children,className=""}:{children:ReactNode;className?:string}){return <div className={`card ${className}`}>{children}</div>}
export function Badge({children,tone="brand"}:{children:ReactNode;tone?:"brand"|"success"|"warning"|"error"}){return <span className="tag" style={tone==="brand"?undefined:{background:`color-mix(in srgb,var(--${tone}) 10%,white)`,color:`var(--${tone})`}}>{children}</span>}
export function Input(props:InputHTMLAttributes<HTMLInputElement>){return <input className={`field ${props.className||""}`} {...props}/>}
export function Select(props:SelectHTMLAttributes<HTMLSelectElement>){return <select className={`field ${props.className||""}`} {...props}/>}
export function SectionHeader({eyebrow,title,description}:{eyebrow?:string;title:string;description?:string}){return <header style={{marginBottom:32}}>{eyebrow&&<p className="eyebrow">{eyebrow}</p>}<h2 className="section-title">{title}</h2>{description&&<p className="muted">{description}</p>}</header>}
export function Tabs({items,active}:{items:string[];active:string}){return <div className="ui-tabs" role="tablist">{items.map(x=><button className="ui-tab" role="tab" aria-selected={x===active} key={x}>{x}</button>)}</div>}
export function Pagination({current=1,total=3}:{current?:number;total?:number}){return <nav className="pagination" aria-label="페이지 이동">{Array.from({length:total},(_,i)=>i+1).map(x=><button className={`page-button ${x===current?"active":""}`} aria-current={x===current?"page":undefined} key={x}>{x}</button>)}</nav>}
export function Dialog({title,children,onClose}:{title:string;children:ReactNode;onClose?:()=>void}){return <div className="dialog-backdrop" role="presentation"><section className="dialog" role="dialog" aria-modal="true" aria-labelledby="dialog-title"><h2 id="dialog-title">{title}</h2>{children}{onClose&&<Button variant="secondary" onClick={onClose}>닫기</Button>}</section></div>}
