import Link from "next/link";
import {Building2,Compass,LayoutDashboard,ShieldCheck,Users} from "lucide-react";
import {ProfileEditor} from "@/components/profile/ProfileEditor";
import {requireUser} from "@/lib/auth/access";
import {getRoleLabel,hasRole,normalizeRoles} from "@/lib/auth/roles";
import {createAdminSupabaseClient} from "@/lib/supabase/admin";
import {getMyLatestHostApplication} from "@/repositories/adminRepository";
export const dynamic="force-dynamic";
export default async function Page({searchParams}:{searchParams:Promise<{error?:string}>}){const{user,profile}=await requireUser("/mypage");const query=await searchParams;const email=profile?.email??user.email??"이메일 정보 없음";const nickname=profile?.nickname??String(user.user_metadata?.nickname??user.email?.split("@")[0]??"회원");const roles=normalizeRoles(profile?.roles);const communityHost=hasRole(profile,"community_host");const spaceHost=hasRole(profile,"space_host");const admin=hasRole(profile,"admin");const hostApplication=await getMyLatestHostApplication(createAdminSupabaseClient(),user.id);
return <section className="section dashboard-shell"><div className="container mypage-container"><div className="section-heading page-heading"><div><p className="eyebrow">My MODIZA</p><h1 className="section-title">마이페이지</h1><p className="muted">프로필과 활동, 운영 권한을 확인하세요.</p></div><Link className="btn btn-primary" href="/dashboard"><LayoutDashboard size={18}/>내 대시보드</Link></div>{query.error==="forbidden"&&<div className="error-summary" style={{marginBottom:20}}>접근 권한이 없습니다.</div>}<ProfileEditor initial={{nickname,email,bio:profile?.bio??"",profileImage:profile?.profileImage??null,mainRegion:profile?.mainRegion??"대구",detailedRegion:profile?.detailedRegion??"",customRegion:profile?.customRegion??"",interestCategories:profile?.interestCategories??[],interestedCategories:profile?.interestedCategories??[],interestedRegions:profile?.interestedRegions??[]}}/>
<section className="dashboard-section profile-role-section"><div className="section-heading"><div><p className="eyebrow">Roles</p><h2>나의 역할과 활동</h2></div><div className="meta">{roles.map(role=><span className="tag" key={role}>{getRoleLabel(role)}</span>)}</div></div><div className="profile-role-grid"><article className="panel role-card"><Compass color="var(--primary)"/><div><h3>일반 회원</h3><p className="muted">커뮤니티를 둘러보고 참여 신청 내역을 확인해요.</p></div><Link className="btn btn-primary btn-small" href="/mypage/applications">내 신청</Link></article><article className="panel role-card"><Users color="var(--primary)"/><div><h3>커뮤니티 운영자</h3><p className="muted">커뮤니티, 신청자, 일정과 체크리스트를 관리해요.</p></div>{communityHost?<Link className="btn btn-primary btn-small" href="/dashboard/communities">내 커뮤니티</Link>:<Link className="btn btn-ghost btn-small" href="/role/start?role=community_host&redirect=/dashboard/communities">커뮤니티 운영 시작하기</Link>}</article><article className="panel role-card"><Building2 color="var(--primary)"/><div><h3>공간 운영자</h3><p className="muted">인증 완료 후 공간 등록과 AI 분석 기능을 사용할 수 있어요.</p></div>{spaceHost?<Link className="btn btn-primary btn-small" href="/dashboard/spaces">내 공간</Link>:hostApplication?.status==="pending"?<><span className="tag application-pending">승인 대기</span><p>공간 운영자 신청을 확인하고 있습니다.</p></>:<Link className="btn btn-ghost btn-small" href="/space-host/apply">공간 운영자 인증 신청</Link>}{hostApplication?.status==="rejected"&&<p className="field-error">반려 사유: {hostApplication.rejectionReason}</p>}</article></div>{admin&&<div className="panel" style={{marginTop:20,display:"flex",justifyContent:"space-between",alignItems:"center",gap:20}}><div><ShieldCheck color="var(--primary)"/><h3>관리자 권한</h3><p className="muted">운영자 신청과 서비스 데이터를 관리합니다.</p></div><Link className="btn btn-primary" href="/admin">관리자 페이지</Link></div>}</section></div></section>}
