"use client";
import Image from "next/image";
import { useRouter } from "next/navigation";
import { ImagePlus, Trash2 } from "lucide-react";
import { useState } from "react";
import { RegionFields } from "@/components/common/RegionFields";
import { PRIMARY_REGION } from "@/constants/taxonomy";
import type { Space, SpaceFormValues, SpaceStatus } from "@/types/space";

const options = { facilities: ["빔프로젝터","스크린","스피커","마이크","화이트보드","긴 테이블","개별 테이블","의자","와이파이","콘센트","주방","화장실","냉난방","주차"], moods: ["조용한","따뜻한","아늑한","감각적인","밝은","자연광이 좋은","전문적인","자유로운","활동적인","독특한"], suitableActivities: ["독서모임","영화모임","글쓰기","네트워킹","스터디","워크숍","촬영","전시","공연","원데이 클래스","보드게임","소규모 행사"], availableDays: ["월","화","수","목","금","토","일"] };
const blank: SpaceFormValues = { name:"", spaceType:"", shortDescription:"", description:"", mainRegion:PRIMARY_REGION, detailedRegion:"", customRegion:"", address:"", addressDetail:"", pricePerHour:0, minimumHours:1, suitableCapacity:undefined, maxCapacity:1, availableDays:[], availableStartTime:"", availableEndTime:"", regularUseAvailable:false, facilities:[], moods:[], suitableActivities:[], noiseLevel:"moderate", foodAllowed:false, alcoholAllowed:false, furnitureMovable:false, parkingAvailable:false, status:"draft" };

export function SpaceForm({ space }: { space?: Space }) {
  const router = useRouter();
  const [values, setValues] = useState<SpaceFormValues>(space ? { ...blank, ...space, customRegion: space.customRegion ?? "" } : blank);
  const [files, setFiles] = useState<File[]>([]);
  const [error, setError] = useState("");
  const [saving, setSaving] = useState(false);
  const toggle = (key: keyof typeof options, value: string) => setValues((current) => ({ ...current, [key]: current[key].includes(value) ? current[key].filter((item) => item !== value) : [...current[key], value] }));
  function add(list: File[]) { if (files.length + (space?.images.length ?? 0) + list.length > 8) return setError("최대 8장까지 업로드할 수 있어요."); if (list.some((file) => !["image/jpeg","image/png","image/webp"].includes(file.type))) return setError("지원하지 않는 이미지 형식이에요."); if (list.some((file) => file.size > 5_242_880)) return setError("이미지 크기는 5MB 이하여야 해요."); setFiles((current) => [...current, ...list.filter((file) => !current.some((item) => item.name === file.name && item.size === file.size))]); setError(""); }
  function validate(status: SpaceStatus) { if (!values.name.trim()) return "공간명을 입력해 주세요."; if (status === "draft") return ""; if (!values.spaceType || !values.shortDescription || !values.description || !values.detailedRegion || !values.address || !values.availableDays.length) return "필수 정보를 모두 입력해 주세요."; if (values.detailedRegion === "기타" && !values.customRegion?.trim()) return "기타 지역명을 입력해 주세요."; if (values.pricePerHour < 0 || values.minimumHours < 1 || values.maxCapacity < 1) return "가격과 인원을 확인해 주세요."; if (values.suitableCapacity && values.suitableCapacity > values.maxCapacity) return "적정 인원은 최대 인원 이하여야 해요."; if (values.availableEndTime && values.availableStartTime && values.availableEndTime <= values.availableStartTime) return "종료 시간은 시작 시간보다 늦어야 해요."; if (!space?.images.length && !files.length) return "대표 이미지를 등록해 주세요."; return ""; }
  async function save(status: SpaceStatus) { const problem = validate(status); if (problem) return setError(problem); setSaving(true); setError(""); try { const normalized = { ...values, mainRegion: PRIMARY_REGION, customRegion: values.detailedRegion === "기타" ? values.customRegion : "", status }; if (space) { const response = await fetch(`/api/spaces/${space.id}`, { method:"PUT", headers:{"Content-Type":"application/json"}, body:JSON.stringify(normalized) }); const result = await response.json(); if (!response.ok) throw new Error(result.message); if (files.length) { const form = new FormData(); files.forEach((file) => form.append("images", file)); const upload = await fetch(`/api/spaces/${space.id}/images`, { method:"POST", body:form }); if (!upload.ok) throw new Error("이미지를 업로드하지 못했어요."); } router.push("/dashboard/spaces"); } else { const form = new FormData(); form.set("values", JSON.stringify(normalized)); form.set("status", status); files.forEach((file) => form.append("images", file)); const response = await fetch("/api/spaces", { method:"POST", body:form }); const result = await response.json(); if (!response.ok) throw new Error(result.message); router.push(`/spaces/register/complete?name=${encodeURIComponent(result.name)}&slug=${result.slug}&status=${result.status}&image=${encodeURIComponent(result.thumbnail_url ?? "")}`); } } catch (caught) { setError(caught instanceof Error && caught.message ? caught.message : "공간 정보를 저장하지 못했어요."); } finally { setSaving(false); } }
  const input = (label: string, key: keyof SpaceFormValues, type = "text") => <label>{label}<input className="field" type={type} value={String(values[key] ?? "")} onChange={(event) => setValues((current) => ({ ...current, [key]: type === "number" ? Number(event.target.value) : event.target.value }))} /></label>;
  const chips = (key: keyof typeof options, title: string) => <fieldset><legend>{title}</legend><div className="category-row">{options[key].map((item) => <button type="button" className={`category ${values[key].includes(item) ? "active" : ""}`} onClick={() => toggle(key, item)} key={item}>{item}</button>)}</div></fieldset>;
  return <div className="form"><section className="panel"><h2>1. 기본 정보</h2><div className="grid form-grid">{input("공간명","name")}<label>공간 유형<select className="field" value={values.spaceType} onChange={(event) => setValues({ ...values, spaceType:event.target.value })}><option value="">선택</option>{["카페","스튜디오","공방","회의실","연습실","복합문화공간","독립 공간","기타"].map((item) => <option key={item}>{item}</option>)}</select></label></div>{input("한 줄 소개","shortDescription")}<label>상세 소개<textarea className="field" rows={5} value={values.description ?? ""} onChange={(event) => setValues({ ...values, description:event.target.value })} /></label></section>
    <section className="panel"><h2>2. 위치 및 지역</h2><RegionFields mainRegion={values.mainRegion} detailedRegion={values.detailedRegion ?? ""} customRegion={values.customRegion} onChange={(region) => setValues((current) => ({ ...current, ...region }))} /><div className="grid form-grid">{input("주소","address")}{input("상세 주소","addressDetail")}</div></section>
    <section className="panel"><h2>3. 이용 조건</h2><div className="grid form-grid">{input("시간당 가격","pricePerHour","number")}{input("최소 이용 시간","minimumHours","number")}{input("적정 인원","suitableCapacity","number")}{input("최대 인원","maxCapacity","number")}{input("시작 시간","availableStartTime","time")}{input("종료 시간","availableEndTime","time")}</div>{chips("availableDays","이용 가능 요일")}</section>
    <section className="panel"><h2>4. 시설 및 분위기</h2>{chips("facilities","시설")}{chips("moods","분위기")}{chips("suitableActivities","적합한 활동")}<label>소음 수준<select className="field" value={values.noiseLevel} onChange={(event) => setValues({ ...values, noiseLevel:event.target.value as SpaceFormValues["noiseLevel"] })}><option value="quiet">조용한 활동만</option><option value="moderate">일반 대화</option><option value="active">활발한 활동</option></select></label><div className="meta">{[["regularUseAvailable","정기 이용"],["foodAllowed","음식물"],["alcoholAllowed","주류"],["furnitureMovable","가구 이동"],["parkingAvailable","주차"]].map(([key,title]) => <label className="checkbox-label" key={key}><input type="checkbox" checked={Boolean(values[key as keyof SpaceFormValues])} onChange={(event) => setValues({ ...values, [key]:event.target.checked })} />{title}</label>)}</div></section>
    <section className="panel"><h2>5. 사진 업로드</h2><label className="upload" onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); add(Array.from(event.dataTransfer.files)); }}><ImagePlus style={{ margin:"auto" }} /><b>사진을 선택하거나 끌어다 놓으세요</b><span>최대 8장 · JPG, PNG, WebP · 5MB 이하</span><input hidden type="file" multiple accept="image/jpeg,image/png,image/webp" onChange={(event) => add(Array.from(event.target.files ?? []))} /></label><div className="grid cards">{space?.images.map((image) => <div className="card" key={image.id}><div className="cover"><Image src={image.publicUrl} fill alt="공간 이미지" />{image.isThumbnail && <span className="tag">대표</span>}</div></div>)}{files.map((file,index) => <div className="card" key={`${file.name}-${index}`}><div className="cover"><Image src={URL.createObjectURL(file)} fill unoptimized alt="미리보기" /></div><button type="button" onClick={() => setFiles(files.filter((_,itemIndex) => itemIndex !== index))}><Trash2 />삭제</button></div>)}</div></section>
    {error && <p className="error-summary">{error}</p>}<div className="meta"><button type="button" className="btn btn-ghost" disabled={saving} onClick={() => void save("draft")}>임시 저장</button><button type="button" className="btn btn-primary" disabled={saving} onClick={() => void save("active")}>{saving ? "저장 중..." : "최종 등록"}</button></div></div>;
}
