import { NextResponse } from "next/server";
import { apiAuthStatus, requireApiUser } from "@/lib/auth/api";
import { cancelSpaceVerification, deleteSpace, getMySpaceById, updateSpace } from "@/repositories/spaceRepository";
import type { UpdateSpaceInput } from "@/types/space";

function failure(error: unknown, fallback: string) { const status = apiAuthStatus(error); return NextResponse.json({ message: status ? error instanceof Error ? error.message : "권한이 없어요." : fallback }, { status: status ?? 500 }); }
export async function GET(_: Request, { params }: { params: Promise<{ id: string }> }) { try { const { supabase } = await requireApiUser("space_host"); const space = await getMySpaceById(supabase, (await params).id); return space ? NextResponse.json(space) : NextResponse.json({ message: "공간을 찾을 수 없어요." }, { status: 404 }); } catch (error) { return failure(error, "공간을 불러오지 못했어요."); } }
export async function PUT(request: Request, { params }: { params: Promise<{ id: string }> }) { try { const { supabase } = await requireApiUser("space_host");const id=(await params).id;const current=await getMySpaceById(supabase,id);if(!current)return NextResponse.json({message:"공간을 찾을 수 없어요."},{status:404});if(["pending","suspended"].includes(current.status))return NextResponse.json({message:current.status==="pending"?"심사 중인 공간은 신청을 취소한 뒤 수정할 수 있어요.":"공개 중지된 공간은 관리자 확인 후 수정할 수 있어요."},{status:409});const values=await request.json() as UpdateSpaceInput;if(!values.preferredContactMethod||!values.privateContact?.trim())return NextResponse.json({message:"협의 연락 방법과 연락 정보를 입력해 주세요."},{status:400});const unchangedLegacy=!current.roadAddress&&values.address===current.address;const selectedRoad=Boolean(values.roadAddress?.trim()&&values.address?.trim()===values.roadAddress.trim());if(!unchangedLegacy&&!selectedRoad)return NextResponse.json({message:"주소 검색을 통해 도로명 주소를 선택해주세요."},{status:400});return NextResponse.json(await updateSpace(supabase,id,values)); } catch (error) { return failure(error, "공간 정보를 저장하지 못했어요."); } }
export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) { try { const { supabase } = await requireApiUser("space_host"); const { action } = await request.json() as { action: "cancel_verification"|"deactivate"|"reactivate" };const id=(await params).id;if(action==="cancel_verification")await cancelSpaceVerification(supabase,id);else if(action==="deactivate"||action==="reactivate"){const result=await supabase.rpc("set_my_space_inactive",{p_space_id:id,p_inactive:action==="deactivate"});if(result.error)throw result.error;}else return NextResponse.json({message:"지원하지 않는 요청이에요."},{status:400});return NextResponse.json({ok:true}); } catch (error) { return failure(error, "공간 상태를 변경하지 못했어요."); } }
export async function DELETE(_: Request, { params }: { params: Promise<{ id: string }> }) { try { const { supabase } = await requireApiUser("space_host"); await deleteSpace(supabase, (await params).id); return NextResponse.json({ ok: true }); } catch (error) { const message = error instanceof Error && error.message === "STORAGE_DELETE_FAILED" ? "이미지 삭제에 실패했어요. 다시 시도해 주세요." : "공간을 삭제하지 못했어요."; return failure(error, message); } }
