import { NextResponse } from "next/server";
import { apiAuthStatus, requireApiUser } from "@/lib/auth/api";
import { changeSpaceStatus, deleteSpace, getMySpaceById, updateSpace } from "@/repositories/spaceRepository";
import type { SpaceStatus, UpdateSpaceInput } from "@/types/space";

function failure(error: unknown, fallback: string) { const status = apiAuthStatus(error); return NextResponse.json({ message: status ? error instanceof Error ? error.message : "권한이 없어요." : fallback }, { status: status ?? 500 }); }
export async function GET(_: Request, { params }: { params: Promise<{ id: string }> }) { try { const { supabase } = await requireApiUser("space_host"); const space = await getMySpaceById(supabase, (await params).id); return space ? NextResponse.json(space) : NextResponse.json({ message: "공간을 찾을 수 없어요." }, { status: 404 }); } catch (error) { return failure(error, "공간을 불러오지 못했어요."); } }
export async function PUT(request: Request, { params }: { params: Promise<{ id: string }> }) { try { const { supabase } = await requireApiUser("space_host"); return NextResponse.json(await updateSpace(supabase, (await params).id, await request.json() as UpdateSpaceInput)); } catch (error) { return failure(error, "공간 정보를 저장하지 못했어요."); } }
export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) { try { const { supabase } = await requireApiUser("space_host"); const { status } = await request.json() as { status: SpaceStatus }; if (!(["draft", "active", "inactive"] as string[]).includes(status)) return NextResponse.json({ message: "공개 상태를 확인해 주세요." }, { status: 400 }); await changeSpaceStatus(supabase, (await params).id, status); return NextResponse.json({ ok: true }); } catch (error) { return failure(error, "공개 상태를 변경하지 못했어요."); } }
export async function DELETE(_: Request, { params }: { params: Promise<{ id: string }> }) { try { const { supabase } = await requireApiUser("space_host"); await deleteSpace(supabase, (await params).id); return NextResponse.json({ ok: true }); } catch (error) { const message = error instanceof Error && error.message === "STORAGE_DELETE_FAILED" ? "이미지 삭제에 실패했어요. 다시 시도해 주세요." : "공간을 삭제하지 못했어요."; return failure(error, message); } }
